### ISSUE TITLE
Wrong slashes on windows and importing 'enum'

### ISSUE THREAD

**Issue by johan-gorter** [cybertim/vscode-gengetset#7]
I tried your promising import assist, the result is not working as expected. I had the following import statements before running `Import Assistant` and I wanted to import `DataAnalysis` and `TaskExecutionContext`.

``` ts
import {Content, ContentType} from './content';
import {DataType} from '../model/data-types';
import {Lookup} from '../common/utilities';
import {ItemsLoader, PageResult, ScreenAction, Item} from './interfaces';
import {FilterConfig} from './reference-field-config';
import {Collection} from '../model/collection';
import {Blueprint} from './blueprint';
import {GenericModel} from '../model/model';
```

The following was the result:

``` ts
import {GenericModel} from '..\model\model';
import {dataType} from '..\model\data-types';
import {enum} from '..\composers\control-composer';
import {enum, id} from '..\control-library\utilities';
import {type} from '..\implementations\operations\unary\subattributes';
import {Content, ContentType} from './content';
import {DataType} from '../model/data-types';
import {Lookup} from '../common/utilities';
import {ItemsLoader, PageResult, ScreenAction, Item, enum, DataAnalysis, TaskExecutionContext} from './interfaces';
import {FilterConfig} from './reference-field-config';
import {Collection} from '../model/collection';
import {Blueprint} from './blueprint';
import {GenericModel} from '../model/model';
```

Two errors stand out immediately: the use of backslashes (I am running on a windows platform) and the import of `enum` from various places.

I hope you can fix this.

**Comment by cybertim** [comment]
Is it possible to show an example of how the 'enum' type is used within the source file and how it is 'exported' within for example the './interfaces' import?
This can help fix the regex which is responsible for this mess :-)

**Comment by johan-gorter** [comment]
This is done like this:

``` ts
export const enum ControlContextMode {
  FIELD_GROUP,
  LIST
}
```

**Comment by cybertim** [comment]
Version 0.2.1 is just published, it should resolve the problem with the enum exports (tested it myself) but the slashes setting (contributed by https://github.com/edotassi) is still untested.
But if it works like advertised it should solve all your problems, please let me know so I can close the issue.

**Comment by johan-gorter** [comment]
I tested your improvements, the enum imports are gone! 
Unfortunately, the slashes are still not working:

``` ts
import {GenericModel} from '..\model\model';
import {createModelFromItem, applyChangesFromModel} from '..\implementations\behaviour\collection-list';
import {type} from '..\implementations\operations\unary\subattributes';
import {Content, ContentType} from './content';
import {DataType} from '../model/data-types';
import {Lookup} from '../common/utilities';
import {ItemsLoader, PageResult, ScreenAction, Item, DataAnalysis, TaskExecutionContext} from './interfaces';
import {FilterConfig} from './reference-field-config';
import {Collection} from '../model/collection';
import {Blueprint} from './blueprint';
```

I am also seeing a `type` import. This looks like the same kind of bug as `enum`. What is also weird is the `id` import. It seems that the algorithm that you use finds the `id` in the following declaration. The `id` here should not be considered to be an import.

``` ts
export interface ListBase {
  id: string;
}
```

**Comment by cybertim** [comment]
Hm, slashes are still a mess, which is weird. Top half is backward and bottom half is forward.
Did you remove all imports before running the plugin? This way we are sure if it is the plugin's fault for combining both forward and backward slashes.

The `id` issue is also weird, because this was a bug I encountered myself with dicts, it should now ignore variables concatenated with `:`. Is the formatting exactly like your example in the comment? Because the plugin can't process this (notice the formatting):

```
  id : string;
  id :string;
```

**Comment by johan-gorter** [comment]
When removing all imports before running the plugin, the result is as follows:

``` ts
import {FilterConfig} from './reference-field-config';
import {PageResult, DataAnalysis, TaskExecutionContext, ScreenAction, ItemsLoader, Item} from './interfaces';
import {Content, ContentType} from './content';
import {GenericModel} from '..\model\model';
import {createModelFromItem, applyChangesFromModel} from '..\implementations\behaviour\collection-list';
import {Blueprint} from './blueprint';
import {type} from '..\implementations\operations\unary\subattributes';
```

**Comment by johan-gorter** [comment]
It seems that the right slash is only used when importing a file from the current folder, like `./content`

**Comment by johan-gorter** [comment]
The formatting is exactly like I commented: `id: string`

**Comment by cybertim** [comment]
Ok, and the `type` could you show an example line where this is used?

**Comment by johan-gorter** [comment]
export:

``` ts
export let type = (input: Calculation<number>): Calculation<string> => {
};
```

presumed import needed:

``` ts
export let isItemsBasedList = (content: Content): content is ItemsBasedList => {
  return content.type === ContentType.LIST;
};
```

**Comment by cybertim** [comment]
please try again, all issues should be fixed now :-)

**Comment by johan-gorter** [comment]
I installed your most recent version (2.2) and guess what? Backslashes everywhere ;-(. Please fix this. 

(note: typescript and javascript are cross-platform, so import statements must use forward slashes. By the way, forward slashes are also supported on windows in file paths, so please make as little exceptions for the windows platform as needed).

**Comment by cybertim** [comment]
All code is now using the `path` library from node to resolve the correct paths (and seperators accordingly). But if one prefers using `/` on all platforms you can  set `genGetSet.useSlashForImportPath` to `true` in the settings, this change all `\\` to `/` for import paths.

**Comment by johan-gorter** [comment]
An import statement in typescript with a backslash in it does not compile, not even on windows. Having a setting to create code that does not compile does not make sense to me.

**Comment by cybertim** [comment]
If that is the case it would make no sense indeed.
But if you can acknowledge that the imports are working _with_ the setting turned on then in the next update I will remove the setting and let it 'turn on' the setting automatically so all platforms will have `/` by default.

**Comment by johan-gorter** [comment]
I tried it with the new setting. The result is promising. The following cases still go wrong:

### Generics

Declaration:

``` ts
export interface Lookup<Target> {
  [key: string]: Target;
}
```

Usage:

``` ts
export interface Dummy {
  x(): Lookup<Object>;
}
```

Expected result: `import` for `Lookup` is added.
Observed result: no `import` is added

### Members

Declaration:

``` ts
export let createItem = (): () => Promise<CollectionItem> () => {
  return (item: Item) => Promise.resolve(undefined);
};
```

Usage:

```
interface X {
  createItem(): Object;
}
```

Expected result: no `import` is added 
Observed result: `import` for `createItem` is added.

**Comment by cybertim** [comment]
in version 0.3.0 the path setting has been removed and switches to `/` on all platforms.
Also the `export interface Lookup<Target>` should work, but the second case will need some extra layer of complexity within the extension.

**Comment by cybertim** [comment]
Almost all issues are resolved, the issue will continue in a new separate Issue #16
